import streamlit as st
from src.data.loaders import detect_and_load_all
from src.ui.tables import render_table_with_download
from src.ui.charts import plot_pie_chart

st.set_page_config(page_title="Device Analysis", layout="wide")
st.title("📱 Device & Usability Analysis")

datasets = detect_and_load_all()

if "device" in datasets and not datasets["device"].empty:
    device_df = datasets["device"]
    
    col1, col2 = st.columns(2)
    with col1:
        fig1 = plot_pie_chart(device_df, values="Active users" if "Active users" in device_df.columns else device_df.columns[1], names="Device category", title="User Traffic by Device")
        if fig1: st.plotly_chart(fig1, width="stretch")
        
    with col2:
        if "Key events" in device_df.columns:
            fig2 = plot_pie_chart(device_df, values="Key events", names="Device category", title="Leads Generated by Device")
            if fig2: st.plotly_chart(fig2, width="stretch")
            
    st.subheader("Device Metrics Table")
    render_table_with_download(device_df, filename="device_analysis.csv", key="device_table")
else:
    st.warning("No device analytics data (`04_Device_GA4.csv`) detected.")